server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://52.163.84.95:3306/department?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

